name: Check HTML links

on: [push]

jobs:
  check_html_links_job:
    runs-on: ubuntu-latest
    name: A job to test our HTML links
    steps:
      - uses: actions/checkout@v5
      - name: get ruby version (used in Github Pages)
        id: ruby-version
        run: echo -n "version=$(curl --silent https://pages.github.com/versions.json | jq --raw-output '.ruby')" >> $GITHUB_OUTPUT
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ steps.ruby-version.outputs.version }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: build blog
        run: bundle exec jekyll build --future
      - name: check links for the home page
        run: npx linkinator --timeout 15000 --recurse _site/index.html --skip '^(https://vue-exercises.ninja-squad.com/exercises/.*)|^(https://twitter.com/.*)'
